#!/usr/bin/env python3
"""
EasyAuth Backup Decryption Tool

Decrypts backup ZIP files generated by the EasyAuth App and outputs
otpauth:// URIs for each 2FA account.

Encryption scheme (matches Flutter backup_service.dart):
  1. Extract salt (16 bytes) and encrypted data from the ZIP archive
  2. Key derivation: PBKDF2-HMAC-SHA256(password, salt, 600000 iterations)
  3. AES-256-GCM decryption: nonce (12 bytes) + ciphertext + GCM tag (16 bytes)
  4. Output otpauth-migration protobuf data as otpauth:// URIs

Usage:
  python decryption.py backup_20260731_120000.zip
  python decryption.py backup_20260731_120000.zip -p yourpassword
  python decryption.py backup.zip -o uris.txt
"""

import argparse
import hashlib
import struct
import sys
import zipfile
from pathlib import Path

try:
    from Cryptodome.Cipher import AES
except ImportError:
    print("Error: pycryptodomex library is required.")
    print("  pip install pycryptodomex")
    sys.exit(1)

# Fixed filenames inside the ZIP (matching backup_service.dart _saltFileName / _dataFileName)
SALT_FILENAME = "salt"
DATA_FILENAME = "data"

# AES-GCM parameters
NONCE_LENGTH = 12    # _nonceLength
TAG_LENGTH = 16      # GCM tag is always 16 bytes

# PBKDF2 iterations (must match backup_service.dart _pbkdf2Iterations)
PBKDF2_ITERATIONS = 600000


def derive_key(password: str, salt: bytes) -> bytes:
    """PBKDF2-HMAC-SHA256(password, salt, 600000) -> 32-byte AES-256 key"""
    return hashlib.pbkdf2_hmac("sha256", password.encode("utf-8"), salt, PBKDF2_ITERATIONS)


def decrypt_backup(zip_path: str, password: str) -> bytes:
    """
    Decrypt a backup ZIP file, returning the otpauth-migration plaintext.

    Raises:
      ValueError: wrong password or corrupted file
      FileNotFoundError: file does not exist
      zipfile.BadZipFile: invalid ZIP file
      KeyError: missing salt or data entry inside the ZIP
    """
    with zipfile.ZipFile(zip_path, "r") as zf:
        # Extract salt
        try:
            salt = zf.read(SALT_FILENAME)
        except KeyError:
            raise KeyError(
                f"Backup format error: missing '{SALT_FILENAME}' entry. "
                f"Please confirm this is an EasyAuth backup file."
            )

        # Extract encrypted data
        try:
            encrypted_data = zf.read(DATA_FILENAME)
        except KeyError:
            raise KeyError(
                f"Backup format error: missing '{DATA_FILENAME}' entry. "
                f"Please confirm this is an EasyAuth backup file."
            )

    if len(salt) != 16:
        raise ValueError(f"Unexpected salt length: {len(salt)} bytes (expected 16)")

    if len(encrypted_data) < NONCE_LENGTH + TAG_LENGTH:
        raise ValueError(
            f"Encrypted data too short: {len(encrypted_data)} bytes "
            f"(need at least {NONCE_LENGTH + TAG_LENGTH})"
        )

    # Layout: nonce (12) + ciphertext + GCM tag (16)
    nonce = encrypted_data[:NONCE_LENGTH]
    ciphertext_with_tag = encrypted_data[NONCE_LENGTH:]

    # Derive key
    key = derive_key(password, salt)

    # AES-256-GCM decryption
    try:
        cipher = AES.new(key, AES.MODE_GCM, nonce=nonce)
        plaintext = cipher.decrypt_and_verify(
            ciphertext_with_tag[:-TAG_LENGTH],
            ciphertext_with_tag[-TAG_LENGTH:],
        )
        return plaintext
    except (ValueError, KeyError) as e:
        raise ValueError(
            f"Decryption failed: the password is incorrect or the backup file is corrupted.\n"
            f"Original error: {e}"
        )


def parse_otpauth_uris(data: bytes) -> list[str]:
    """
    Extract otpauth:// URIs from an otpauth-migration protobuf message.

    Parses the Google Authenticator migration protocol (Protocol Buffers).
    Message format: MigrationPayload { repeated OtpParameters otp_parameters }

    OtpParameters fields:
      field 1: secret   (bytes, base32)
      field 2: name     (string)
      field 3: issuer   (string)
      field 4: algorithm (int, 0=unspecified 1=SHA1 2=SHA256 3=SHA512 4=MD5)
      field 5: digits   (int, 0=unspecified 1=6 2=8)
      field 6: type     (int, 0=unspecified 1=HOTP 2=TOTP)
      field 7: counter  (int64)
    """
    import base64

    ALGORITHMS = {0: "SHA1", 1: "SHA1", 2: "SHA256", 3: "SHA512", 4: "MD5"}
    DIGITS = {0: 6, 1: 6, 2: 8}
    TYPES = {0: "totp", 1: "hotp", 2: "totp"}

    uris = []
    pos = 0

    try:
        while pos < len(data):
            tag, pos = read_varint(data, pos)
            field_number = tag >> 3
            wire_type = tag & 0x07

            if field_number == 1 and wire_type == 2:
                # otp_parameters: length-delimited sub-message
                length, pos = read_varint(data, pos)
                sub_data = data[pos : pos + length]
                pos += length
                uri = parse_otp_parameter(sub_data, ALGORITHMS, DIGITS, TYPES)
                if uri:
                    uris.append(uri)
            else:
                # Skip other fields
                pos = skip_field(data, pos, wire_type)
    except (IndexError, ValueError):
        pass

    # Fallback: if protobuf parsing produced nothing, try plain text
    if not uris:
        try:
            text = data.decode("utf-8")
            if text.startswith("otpauth://"):
                uris = [line for line in text.splitlines() if line.strip()]
        except UnicodeDecodeError:
            pass

    return uris


def parse_otp_parameter(data: bytes, algorithms: dict, digits_map: dict,
                        types: dict) -> str | None:
    """Parse a single OtpParameters protobuf message into an otpauth:// URI."""
    import base64
    import urllib.parse

    secret = b""
    name = ""
    issuer = ""
    algorithm = 0
    digits = 0
    otp_type = 0
    counter = 0

    pos = 0
    while pos < len(data):
        tag, pos = read_varint(data, pos)
        field_number = tag >> 3
        wire_type = tag & 0x07

        if field_number == 1 and wire_type == 2:  # secret (bytes)
            length, pos = read_varint(data, pos)
            secret = data[pos : pos + length]
            pos += length
        elif field_number == 2 and wire_type == 2:  # name (string)
            length, pos = read_varint(data, pos)
            name = data[pos : pos + length].decode("utf-8", errors="replace")
            pos += length
        elif field_number == 3 and wire_type == 2:  # issuer (string)
            length, pos = read_varint(data, pos)
            issuer = data[pos : pos + length].decode("utf-8", errors="replace")
            pos += length
        elif field_number == 4 and wire_type == 0:  # algorithm (varint)
            algorithm, pos = read_varint(data, pos)
        elif field_number == 5 and wire_type == 0:  # digits (varint)
            digits, pos = read_varint(data, pos)
        elif field_number == 6 and wire_type == 0:  # type (varint)
            otp_type, pos = read_varint(data, pos)
        elif field_number == 7 and wire_type == 0:  # counter (varint)
            counter, pos = read_varint(data, pos)
        else:
            pos = skip_field(data, pos, wire_type)

    if not secret:
        return None

    # Base32-encode the secret
    secret_b32 = base64.b32encode(secret).decode("ascii").rstrip("=")

    # Resolve enums
    algo = algorithms.get(algorithm, "SHA1")
    dig = digits_map.get(digits, 6)
    typ = types.get(otp_type, "totp")

    # Build otpauth URI
    label = urllib.parse.quote(name, safe="")
    params = [f"secret={secret_b32}"]
    if issuer:
        params.append(f"issuer={urllib.parse.quote(issuer, safe='')}")
    params.append(f"algorithm={algo}")
    params.append(f"digits={dig}")
    params.append(f"period=30")

    uri = f"otpauth://{typ}/{label}?{'&'.join(params)}"
    return uri


def read_varint(data: bytes, pos: int) -> tuple[int, int]:
    """Read a protobuf varint, returning (value, new_position)."""
    result = 0
    shift = 0
    while pos < len(data):
        byte = data[pos]
        pos += 1
        result |= (byte & 0x7F) << shift
        if not (byte & 0x80):
            return result, pos
        shift += 7
    raise IndexError("varint ran past end of data")


def skip_field(data: bytes, pos: int, wire_type: int) -> int:
    """Skip a protobuf field of the given wire type."""
    if wire_type == 0:  # varint
        while pos < len(data) and (data[pos] & 0x80):
            pos += 1
        return pos + 1 if pos < len(data) else pos
    elif wire_type == 2:  # length-delimited
        if pos >= len(data):
            return pos
        length, pos = read_varint(data, pos)
        return pos + length
    elif wire_type == 5:  # 32-bit
        return pos + 4
    elif wire_type == 1:  # 64-bit
        return pos + 8
    return pos


def main():
    parser = argparse.ArgumentParser(
        description="EasyAuth Backup Decryption Tool",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python decryption.py backup_20260731_120000.zip
  python decryption.py backup.zip -p MySecret123
  python decryption.py backup.zip -o decrypted_uris.txt
        """,
    )
    parser.add_argument(
        "zipfile",
        help="Path to the EasyAuth backup ZIP file",
    )
    parser.add_argument(
        "-p", "--password",
        help="Backup password (if not provided, you will be prompted)",
    )
    parser.add_argument(
        "-o", "--output",
        help="Output file path (default: stdout)",
    )
    parser.add_argument(
        "--raw",
        action="store_true",
        help="Output raw decrypted data without protobuf decoding",
    )
    args = parser.parse_args()

    zip_path = Path(args.zipfile)
    if not zip_path.exists():
        print(f"Error: file not found: {zip_path}")
        sys.exit(1)

    # Get password
    password = args.password
    if not password:
        import getpass
        password = getpass.getpass("Backup password: ")
        if not password:
            print("Error: password cannot be empty")
            sys.exit(1)

    # Decrypt
    print(f"Decrypting: {zip_path.name} ...")
    try:
        plaintext = decrypt_backup(str(zip_path), password)
    except ValueError as e:
        print(f"\nDecryption failed: {e}")
        sys.exit(1)
    except FileNotFoundError as e:
        print(f"\nFile error: {e}")
        sys.exit(1)
    except zipfile.BadZipFile:
        print(f"\nError: '{zip_path}' is not a valid ZIP file")
        sys.exit(1)
    except KeyError as e:
        print(f"\nError: {e}")
        sys.exit(1)

    print(f"Decryption successful! Plaintext size: {len(plaintext)} bytes\n")

    # Output
    if args.raw:
        output = plaintext.decode("utf-8", errors="replace")
    else:
        uris = parse_otpauth_uris(plaintext)
        if uris:
            output = "\n".join(uris)
            print(f"Found {len(uris)} 2FA account(s):\n")
        else:
            output = plaintext.decode("utf-8", errors="replace")
            print("Could not parse protobuf, showing raw data:\n")

    if args.output:
        Path(args.output).write_text(output, encoding="utf-8")
        print(f"Saved to: {args.output}")
    else:
        print(output)


if __name__ == "__main__":
    main()
